language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
before-script:
  - npm install
script:
  - npm run test:coveralls
notifications:
  slack: andela:Bsl86DcFayVaPuGBjIWfrjI4
